// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/net.proto

package com.zaly.proto.core;

public final class Net {
  private Net() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code core.TransportDataHeaderKey}
   */
  public enum TransportDataHeaderKey
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HeaderInvalid = 0;</code>
     */
    HeaderInvalid(0),
    /**
     * <code>HeaderErrorCode = 1;</code>
     */
    HeaderErrorCode(1),
    /**
     * <code>HeaderErrorInfo = 2;</code>
     */
    HeaderErrorInfo(2),
    /**
     * <code>HeaderSessionid = 3;</code>
     */
    HeaderSessionid(3),
    /**
     * <pre>
     * the value must be set for websocket and zaly request.
     * 
     * (scheme://)?host:(port)?(/path)?
     * 
     * http://127.0.0.1
     * http://127.0.0.1:8080
     * http://127.0.0.1/child-dir/
     * zaly://127.0.0.1
     * zaly://127.0.0.1:3681
     * ws://127.0.0.1:8888/child-dir/
     * </pre>
     *
     * <code>HeaderHostUrl = 4;</code>
     */
    HeaderHostUrl(4),
    /**
     * <pre>
     * zalyUrl
     * </pre>
     *
     * <code>HeaderReferer = 5;</code>
     */
    HeaderReferer(5),
    /**
     * <pre>
     * the value is a string.
     * the jsRequest in web must set the value with the browser user agent.
     * </pre>
     *
     * <code>HeaderUserAgent = 6;</code>
     */
    HeaderUserAgent(6),
    /**
     * <pre>
     * whether the response can be cached by the client.
     * </pre>
     *
     * <code>HeaderAllowCache = 7;</code>
     */
    HeaderAllowCache(7),
    /**
     * <pre>
     * (string)UserClientLangType please when set its value.
     * </pre>
     *
     * <code>HeaderUserClientLang = 8;</code>
     */
    HeaderUserClientLang(8),
    /**
     * <pre>
     * Reference: (message Version).json
     * </pre>
     *
     * <code>HeaderApplicationVersion = 10;</code>
     */
    HeaderApplicationVersion(10),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>HeaderInvalid = 0;</code>
     */
    public static final int HeaderInvalid_VALUE = 0;
    /**
     * <code>HeaderErrorCode = 1;</code>
     */
    public static final int HeaderErrorCode_VALUE = 1;
    /**
     * <code>HeaderErrorInfo = 2;</code>
     */
    public static final int HeaderErrorInfo_VALUE = 2;
    /**
     * <code>HeaderSessionid = 3;</code>
     */
    public static final int HeaderSessionid_VALUE = 3;
    /**
     * <pre>
     * the value must be set for websocket and zaly request.
     * 
     * (scheme://)?host:(port)?(/path)?
     * 
     * http://127.0.0.1
     * http://127.0.0.1:8080
     * http://127.0.0.1/child-dir/
     * zaly://127.0.0.1
     * zaly://127.0.0.1:3681
     * ws://127.0.0.1:8888/child-dir/
     * </pre>
     *
     * <code>HeaderHostUrl = 4;</code>
     */
    public static final int HeaderHostUrl_VALUE = 4;
    /**
     * <pre>
     * zalyUrl
     * </pre>
     *
     * <code>HeaderReferer = 5;</code>
     */
    public static final int HeaderReferer_VALUE = 5;
    /**
     * <pre>
     * the value is a string.
     * the jsRequest in web must set the value with the browser user agent.
     * </pre>
     *
     * <code>HeaderUserAgent = 6;</code>
     */
    public static final int HeaderUserAgent_VALUE = 6;
    /**
     * <pre>
     * whether the response can be cached by the client.
     * </pre>
     *
     * <code>HeaderAllowCache = 7;</code>
     */
    public static final int HeaderAllowCache_VALUE = 7;
    /**
     * <pre>
     * (string)UserClientLangType please when set its value.
     * </pre>
     *
     * <code>HeaderUserClientLang = 8;</code>
     */
    public static final int HeaderUserClientLang_VALUE = 8;
    /**
     * <pre>
     * Reference: (message Version).json
     * </pre>
     *
     * <code>HeaderApplicationVersion = 10;</code>
     */
    public static final int HeaderApplicationVersion_VALUE = 10;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TransportDataHeaderKey valueOf(int value) {
      return forNumber(value);
    }

    public static TransportDataHeaderKey forNumber(int value) {
      switch (value) {
        case 0: return HeaderInvalid;
        case 1: return HeaderErrorCode;
        case 2: return HeaderErrorInfo;
        case 3: return HeaderSessionid;
        case 4: return HeaderHostUrl;
        case 5: return HeaderReferer;
        case 6: return HeaderUserAgent;
        case 7: return HeaderAllowCache;
        case 8: return HeaderUserClientLang;
        case 10: return HeaderApplicationVersion;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TransportDataHeaderKey>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TransportDataHeaderKey> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TransportDataHeaderKey>() {
            public TransportDataHeaderKey findValueByNumber(int number) {
              return TransportDataHeaderKey.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zaly.proto.core.Net.getDescriptor().getEnumTypes().get(0);
    }

    private static final TransportDataHeaderKey[] VALUES = values();

    public static TransportDataHeaderKey valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TransportDataHeaderKey(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:core.TransportDataHeaderKey)
  }

  /**
   * Protobuf enum {@code core.UserClientLangType}
   */
  public enum UserClientLangType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UserClientLangEN = 0;</code>
     */
    UserClientLangEN(0),
    /**
     * <code>UserClientLangZH = 1;</code>
     */
    UserClientLangZH(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UserClientLangEN = 0;</code>
     */
    public static final int UserClientLangEN_VALUE = 0;
    /**
     * <code>UserClientLangZH = 1;</code>
     */
    public static final int UserClientLangZH_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserClientLangType valueOf(int value) {
      return forNumber(value);
    }

    public static UserClientLangType forNumber(int value) {
      switch (value) {
        case 0: return UserClientLangEN;
        case 1: return UserClientLangZH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserClientLangType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserClientLangType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserClientLangType>() {
            public UserClientLangType findValueByNumber(int number) {
              return UserClientLangType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zaly.proto.core.Net.getDescriptor().getEnumTypes().get(1);
    }

    private static final UserClientLangType[] VALUES = values();

    public static UserClientLangType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserClientLangType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:core.UserClientLangType)
  }

  /**
   * Protobuf enum {@code core.GatewayType}
   */
  public enum GatewayType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GatewayInvalid = 0;</code>
     */
    GatewayInvalid(0),
    /**
     * <code>GatewayWebsocket = 1;</code>
     */
    GatewayWebsocket(1),
    /**
     * <code>GatewayZaly = 2;</code>
     */
    GatewayZaly(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GatewayInvalid = 0;</code>
     */
    public static final int GatewayInvalid_VALUE = 0;
    /**
     * <code>GatewayWebsocket = 1;</code>
     */
    public static final int GatewayWebsocket_VALUE = 1;
    /**
     * <code>GatewayZaly = 2;</code>
     */
    public static final int GatewayZaly_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GatewayType valueOf(int value) {
      return forNumber(value);
    }

    public static GatewayType forNumber(int value) {
      switch (value) {
        case 0: return GatewayInvalid;
        case 1: return GatewayWebsocket;
        case 2: return GatewayZaly;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GatewayType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GatewayType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GatewayType>() {
            public GatewayType findValueByNumber(int number) {
              return GatewayType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zaly.proto.core.Net.getDescriptor().getEnumTypes().get(2);
    }

    private static final GatewayType[] VALUES = values();

    public static GatewayType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GatewayType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:core.GatewayType)
  }

  /**
   * Protobuf enum {@code core.UserClientType}
   */
  public enum UserClientType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UserClientMobileInvalid = 0;</code>
     */
    UserClientMobileInvalid(0),
    /**
     * <code>UserClientMobileApp = 1;</code>
     */
    UserClientMobileApp(1),
    /**
     * <code>UserClientWeb = 2;</code>
     */
    UserClientWeb(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UserClientMobileInvalid = 0;</code>
     */
    public static final int UserClientMobileInvalid_VALUE = 0;
    /**
     * <code>UserClientMobileApp = 1;</code>
     */
    public static final int UserClientMobileApp_VALUE = 1;
    /**
     * <code>UserClientWeb = 2;</code>
     */
    public static final int UserClientWeb_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserClientType valueOf(int value) {
      return forNumber(value);
    }

    public static UserClientType forNumber(int value) {
      switch (value) {
        case 0: return UserClientMobileInvalid;
        case 1: return UserClientMobileApp;
        case 2: return UserClientWeb;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserClientType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserClientType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserClientType>() {
            public UserClientType findValueByNumber(int number) {
              return UserClientType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zaly.proto.core.Net.getDescriptor().getEnumTypes().get(3);
    }

    private static final UserClientType[] VALUES = values();

    public static UserClientType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserClientType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:core.UserClientType)
  }

  /**
   * Protobuf enum {@code core.HttpQueryType}
   */
  public enum HttpQueryType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HttpQueryInvalid = 0;</code>
     */
    HttpQueryInvalid(0),
    /**
     * <code>HttpQueryGet = 1;</code>
     */
    HttpQueryGet(1),
    /**
     * <code>HttpQueryPost = 2;</code>
     */
    HttpQueryPost(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>HttpQueryInvalid = 0;</code>
     */
    public static final int HttpQueryInvalid_VALUE = 0;
    /**
     * <code>HttpQueryGet = 1;</code>
     */
    public static final int HttpQueryGet_VALUE = 1;
    /**
     * <code>HttpQueryPost = 2;</code>
     */
    public static final int HttpQueryPost_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static HttpQueryType valueOf(int value) {
      return forNumber(value);
    }

    public static HttpQueryType forNumber(int value) {
      switch (value) {
        case 0: return HttpQueryInvalid;
        case 1: return HttpQueryGet;
        case 2: return HttpQueryPost;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HttpQueryType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        HttpQueryType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HttpQueryType>() {
            public HttpQueryType findValueByNumber(int number) {
              return HttpQueryType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zaly.proto.core.Net.getDescriptor().getEnumTypes().get(4);
    }

    private static final HttpQueryType[] VALUES = values();

    public static HttpQueryType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private HttpQueryType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:core.HttpQueryType)
  }

  /**
   * <pre>
   * there are lots of mime.types here:
   * http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
   * </pre>
   *
   * Protobuf enum {@code core.FileType}
   */
  public enum FileType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FileInvalid = 0;</code>
     */
    FileInvalid(0),
    /**
     * <pre>
     * the server should find the exactly extension, ex: http://php.net/manual/en/function.mime-content-type.php
     * </pre>
     *
     * <code>FileImage = 1;</code>
     */
    FileImage(1),
    /**
     * <pre>
     * the server should find the exactly extension, ex: http://php.net/manual/en/function.mime-content-type.php
     * </pre>
     *
     * <code>FileAudio = 2;</code>
     */
    FileAudio(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FileInvalid = 0;</code>
     */
    public static final int FileInvalid_VALUE = 0;
    /**
     * <pre>
     * the server should find the exactly extension, ex: http://php.net/manual/en/function.mime-content-type.php
     * </pre>
     *
     * <code>FileImage = 1;</code>
     */
    public static final int FileImage_VALUE = 1;
    /**
     * <pre>
     * the server should find the exactly extension, ex: http://php.net/manual/en/function.mime-content-type.php
     * </pre>
     *
     * <code>FileAudio = 2;</code>
     */
    public static final int FileAudio_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FileType valueOf(int value) {
      return forNumber(value);
    }

    public static FileType forNumber(int value) {
      switch (value) {
        case 0: return FileInvalid;
        case 1: return FileImage;
        case 2: return FileAudio;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FileType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FileType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FileType>() {
            public FileType findValueByNumber(int number) {
              return FileType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zaly.proto.core.Net.getDescriptor().getEnumTypes().get(5);
    }

    private static final FileType[] VALUES = values();

    public static FileType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FileType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:core.FileType)
  }

  /**
   * Protobuf enum {@code core.DataWriteType}
   */
  public enum DataWriteType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * db = requestValue
     * </pre>
     *
     * <code>WriteUpdate = 0;</code>
     */
    WriteUpdate(0),
    /**
     * <pre>
     * db = db + requestValue
     * </pre>
     *
     * <code>WriteAdd = 1;</code>
     */
    WriteAdd(1),
    /**
     * <pre>
     * db = db - requestValue
     * </pre>
     *
     * <code>WriteDel = 2;</code>
     */
    WriteDel(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * db = requestValue
     * </pre>
     *
     * <code>WriteUpdate = 0;</code>
     */
    public static final int WriteUpdate_VALUE = 0;
    /**
     * <pre>
     * db = db + requestValue
     * </pre>
     *
     * <code>WriteAdd = 1;</code>
     */
    public static final int WriteAdd_VALUE = 1;
    /**
     * <pre>
     * db = db - requestValue
     * </pre>
     *
     * <code>WriteDel = 2;</code>
     */
    public static final int WriteDel_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataWriteType valueOf(int value) {
      return forNumber(value);
    }

    public static DataWriteType forNumber(int value) {
      switch (value) {
        case 0: return WriteUpdate;
        case 1: return WriteAdd;
        case 2: return WriteDel;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataWriteType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataWriteType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataWriteType>() {
            public DataWriteType findValueByNumber(int number) {
              return DataWriteType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zaly.proto.core.Net.getDescriptor().getEnumTypes().get(6);
    }

    private static final DataWriteType[] VALUES = values();

    public static DataWriteType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DataWriteType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:core.DataWriteType)
  }

  public interface TransportDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.TransportData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string action = 1;</code>
     */
    java.lang.String getAction();
    /**
     * <code>string action = 1;</code>
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <code>.google.protobuf.Any body = 2;</code>
     */
    boolean hasBody();
    /**
     * <code>.google.protobuf.Any body = 2;</code>
     */
    com.google.protobuf.Any getBody();
    /**
     * <code>.google.protobuf.Any body = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getBodyOrBuilder();

    /**
     * <pre>
     * transfrom TransportDataHeaderKey to string.
     * key = "_" + TransportDataHeaderKey
     * ex: "_1", "_9"
     * 
     * Q: why donot use TransportDataHeaderKey directly?
     * A: javascript(json) doesnot support int key in object.
     * Q: why donnot use string(TransportDataHeaderKey)?
     * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
     * </pre>
     *
     * <code>map&lt;string, string&gt; header = 3;</code>
     */
    int getHeaderCount();
    /**
     * <pre>
     * transfrom TransportDataHeaderKey to string.
     * key = "_" + TransportDataHeaderKey
     * ex: "_1", "_9"
     * 
     * Q: why donot use TransportDataHeaderKey directly?
     * A: javascript(json) doesnot support int key in object.
     * Q: why donnot use string(TransportDataHeaderKey)?
     * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
     * </pre>
     *
     * <code>map&lt;string, string&gt; header = 3;</code>
     */
    boolean containsHeader(
        java.lang.String key);
    /**
     * Use {@link #getHeaderMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getHeader();
    /**
     * <pre>
     * transfrom TransportDataHeaderKey to string.
     * key = "_" + TransportDataHeaderKey
     * ex: "_1", "_9"
     * 
     * Q: why donot use TransportDataHeaderKey directly?
     * A: javascript(json) doesnot support int key in object.
     * Q: why donnot use string(TransportDataHeaderKey)?
     * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
     * </pre>
     *
     * <code>map&lt;string, string&gt; header = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getHeaderMap();
    /**
     * <pre>
     * transfrom TransportDataHeaderKey to string.
     * key = "_" + TransportDataHeaderKey
     * ex: "_1", "_9"
     * 
     * Q: why donot use TransportDataHeaderKey directly?
     * A: javascript(json) doesnot support int key in object.
     * Q: why donnot use string(TransportDataHeaderKey)?
     * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
     * </pre>
     *
     * <code>map&lt;string, string&gt; header = 3;</code>
     */

    java.lang.String getHeaderOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     * transfrom TransportDataHeaderKey to string.
     * key = "_" + TransportDataHeaderKey
     * ex: "_1", "_9"
     * 
     * Q: why donot use TransportDataHeaderKey directly?
     * A: javascript(json) doesnot support int key in object.
     * Q: why donnot use string(TransportDataHeaderKey)?
     * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
     * </pre>
     *
     * <code>map&lt;string, string&gt; header = 3;</code>
     */

    java.lang.String getHeaderOrThrow(
        java.lang.String key);

    /**
     * <pre>
     * uniqid for blockRequest
     * the default php config doesnot support bcmath required by int64
     * </pre>
     *
     * <code>int64 packageId = 4;</code>
     */
    long getPackageId();
  }
  /**
   * Protobuf type {@code core.TransportData}
   */
  public  static final class TransportData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.TransportData)
      TransportDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransportData.newBuilder() to construct.
    private TransportData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransportData() {
      action_ = "";
      packageId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransportData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              action_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (body_ != null) {
                subBuilder = body_.toBuilder();
              }
              body_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body_);
                body_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                header_ = com.google.protobuf.MapField.newMapField(
                    HeaderDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              header__ = input.readMessage(
                  HeaderDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              header_.getMutableMap().put(
                  header__.getKey(), header__.getValue());
              break;
            }
            case 32: {

              packageId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zaly.proto.core.Net.internal_static_core_TransportData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetHeader();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zaly.proto.core.Net.internal_static_core_TransportData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zaly.proto.core.Net.TransportData.class, com.zaly.proto.core.Net.TransportData.Builder.class);
    }

    private int bitField0_;
    public static final int ACTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object action_;
    /**
     * <code>string action = 1;</code>
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <code>string action = 1;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.Any body_;
    /**
     * <code>.google.protobuf.Any body = 2;</code>
     */
    public boolean hasBody() {
      return body_ != null;
    }
    /**
     * <code>.google.protobuf.Any body = 2;</code>
     */
    public com.google.protobuf.Any getBody() {
      return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
    }
    /**
     * <code>.google.protobuf.Any body = 2;</code>
     */
    public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
      return getBody();
    }

    public static final int HEADER_FIELD_NUMBER = 3;
    private static final class HeaderDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.zaly.proto.core.Net.internal_static_core_TransportData_HeaderEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> header_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetHeader() {
      if (header_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            HeaderDefaultEntryHolder.defaultEntry);
      }
      return header_;
    }

    public int getHeaderCount() {
      return internalGetHeader().getMap().size();
    }
    /**
     * <pre>
     * transfrom TransportDataHeaderKey to string.
     * key = "_" + TransportDataHeaderKey
     * ex: "_1", "_9"
     * 
     * Q: why donot use TransportDataHeaderKey directly?
     * A: javascript(json) doesnot support int key in object.
     * Q: why donnot use string(TransportDataHeaderKey)?
     * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
     * </pre>
     *
     * <code>map&lt;string, string&gt; header = 3;</code>
     */

    public boolean containsHeader(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetHeader().getMap().containsKey(key);
    }
    /**
     * Use {@link #getHeaderMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getHeader() {
      return getHeaderMap();
    }
    /**
     * <pre>
     * transfrom TransportDataHeaderKey to string.
     * key = "_" + TransportDataHeaderKey
     * ex: "_1", "_9"
     * 
     * Q: why donot use TransportDataHeaderKey directly?
     * A: javascript(json) doesnot support int key in object.
     * Q: why donnot use string(TransportDataHeaderKey)?
     * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
     * </pre>
     *
     * <code>map&lt;string, string&gt; header = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getHeaderMap() {
      return internalGetHeader().getMap();
    }
    /**
     * <pre>
     * transfrom TransportDataHeaderKey to string.
     * key = "_" + TransportDataHeaderKey
     * ex: "_1", "_9"
     * 
     * Q: why donot use TransportDataHeaderKey directly?
     * A: javascript(json) doesnot support int key in object.
     * Q: why donnot use string(TransportDataHeaderKey)?
     * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
     * </pre>
     *
     * <code>map&lt;string, string&gt; header = 3;</code>
     */

    public java.lang.String getHeaderOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeader().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * transfrom TransportDataHeaderKey to string.
     * key = "_" + TransportDataHeaderKey
     * ex: "_1", "_9"
     * 
     * Q: why donot use TransportDataHeaderKey directly?
     * A: javascript(json) doesnot support int key in object.
     * Q: why donnot use string(TransportDataHeaderKey)?
     * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
     * </pre>
     *
     * <code>map&lt;string, string&gt; header = 3;</code>
     */

    public java.lang.String getHeaderOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeader().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int PACKAGEID_FIELD_NUMBER = 4;
    private long packageId_;
    /**
     * <pre>
     * uniqid for blockRequest
     * the default php config doesnot support bcmath required by int64
     * </pre>
     *
     * <code>int64 packageId = 4;</code>
     */
    public long getPackageId() {
      return packageId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getActionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, action_);
      }
      if (body_ != null) {
        output.writeMessage(2, getBody());
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetHeader(),
          HeaderDefaultEntryHolder.defaultEntry,
          3);
      if (packageId_ != 0L) {
        output.writeInt64(4, packageId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getActionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, action_);
      }
      if (body_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBody());
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetHeader().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        header__ = HeaderDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, header__);
      }
      if (packageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, packageId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zaly.proto.core.Net.TransportData)) {
        return super.equals(obj);
      }
      com.zaly.proto.core.Net.TransportData other = (com.zaly.proto.core.Net.TransportData) obj;

      boolean result = true;
      result = result && getAction()
          .equals(other.getAction());
      result = result && (hasBody() == other.hasBody());
      if (hasBody()) {
        result = result && getBody()
            .equals(other.getBody());
      }
      result = result && internalGetHeader().equals(
          other.internalGetHeader());
      result = result && (getPackageId()
          == other.getPackageId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      if (!internalGetHeader().getMap().isEmpty()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + internalGetHeader().hashCode();
      }
      hash = (37 * hash) + PACKAGEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPackageId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zaly.proto.core.Net.TransportData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.core.Net.TransportData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.core.Net.TransportData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.core.Net.TransportData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.core.Net.TransportData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.core.Net.TransportData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.core.Net.TransportData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.core.Net.TransportData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.core.Net.TransportData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zaly.proto.core.Net.TransportData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.core.Net.TransportData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.core.Net.TransportData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zaly.proto.core.Net.TransportData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code core.TransportData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.TransportData)
        com.zaly.proto.core.Net.TransportDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zaly.proto.core.Net.internal_static_core_TransportData_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetHeader();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableHeader();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zaly.proto.core.Net.internal_static_core_TransportData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zaly.proto.core.Net.TransportData.class, com.zaly.proto.core.Net.TransportData.Builder.class);
      }

      // Construct using com.zaly.proto.core.Net.TransportData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        action_ = "";

        if (bodyBuilder_ == null) {
          body_ = null;
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }
        internalGetMutableHeader().clear();
        packageId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zaly.proto.core.Net.internal_static_core_TransportData_descriptor;
      }

      public com.zaly.proto.core.Net.TransportData getDefaultInstanceForType() {
        return com.zaly.proto.core.Net.TransportData.getDefaultInstance();
      }

      public com.zaly.proto.core.Net.TransportData build() {
        com.zaly.proto.core.Net.TransportData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zaly.proto.core.Net.TransportData buildPartial() {
        com.zaly.proto.core.Net.TransportData result = new com.zaly.proto.core.Net.TransportData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.action_ = action_;
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        result.header_ = internalGetHeader();
        result.header_.makeImmutable();
        result.packageId_ = packageId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zaly.proto.core.Net.TransportData) {
          return mergeFrom((com.zaly.proto.core.Net.TransportData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zaly.proto.core.Net.TransportData other) {
        if (other == com.zaly.proto.core.Net.TransportData.getDefaultInstance()) return this;
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          onChanged();
        }
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        internalGetMutableHeader().mergeFrom(
            other.internalGetHeader());
        if (other.getPackageId() != 0L) {
          setPackageId(other.getPackageId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zaly.proto.core.Net.TransportData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zaly.proto.core.Net.TransportData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object action_ = "";
      /**
       * <code>string action = 1;</code>
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string action = 1;</code>
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string action = 1;</code>
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string action = 1;</code>
       */
      public Builder clearAction() {
        
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <code>string action = 1;</code>
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        action_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any body_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> bodyBuilder_;
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public boolean hasBody() {
        return bodyBuilder_ != null || body_ != null;
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public com.google.protobuf.Any getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder setBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder setBody(
          com.google.protobuf.Any.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder mergeBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (body_ != null) {
            body_ =
              com.google.protobuf.Any.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = null;
          onChanged();
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public com.google.protobuf.Any.Builder getBodyBuilder() {
        
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : body_;
        }
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> header_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetHeader() {
        if (header_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              HeaderDefaultEntryHolder.defaultEntry);
        }
        return header_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableHeader() {
        onChanged();;
        if (header_ == null) {
          header_ = com.google.protobuf.MapField.newMapField(
              HeaderDefaultEntryHolder.defaultEntry);
        }
        if (!header_.isMutable()) {
          header_ = header_.copy();
        }
        return header_;
      }

      public int getHeaderCount() {
        return internalGetHeader().getMap().size();
      }
      /**
       * <pre>
       * transfrom TransportDataHeaderKey to string.
       * key = "_" + TransportDataHeaderKey
       * ex: "_1", "_9"
       * 
       * Q: why donot use TransportDataHeaderKey directly?
       * A: javascript(json) doesnot support int key in object.
       * Q: why donnot use string(TransportDataHeaderKey)?
       * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
       * </pre>
       *
       * <code>map&lt;string, string&gt; header = 3;</code>
       */

      public boolean containsHeader(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetHeader().getMap().containsKey(key);
      }
      /**
       * Use {@link #getHeaderMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getHeader() {
        return getHeaderMap();
      }
      /**
       * <pre>
       * transfrom TransportDataHeaderKey to string.
       * key = "_" + TransportDataHeaderKey
       * ex: "_1", "_9"
       * 
       * Q: why donot use TransportDataHeaderKey directly?
       * A: javascript(json) doesnot support int key in object.
       * Q: why donnot use string(TransportDataHeaderKey)?
       * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
       * </pre>
       *
       * <code>map&lt;string, string&gt; header = 3;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getHeaderMap() {
        return internalGetHeader().getMap();
      }
      /**
       * <pre>
       * transfrom TransportDataHeaderKey to string.
       * key = "_" + TransportDataHeaderKey
       * ex: "_1", "_9"
       * 
       * Q: why donot use TransportDataHeaderKey directly?
       * A: javascript(json) doesnot support int key in object.
       * Q: why donnot use string(TransportDataHeaderKey)?
       * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
       * </pre>
       *
       * <code>map&lt;string, string&gt; header = 3;</code>
       */

      public java.lang.String getHeaderOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetHeader().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * transfrom TransportDataHeaderKey to string.
       * key = "_" + TransportDataHeaderKey
       * ex: "_1", "_9"
       * 
       * Q: why donot use TransportDataHeaderKey directly?
       * A: javascript(json) doesnot support int key in object.
       * Q: why donnot use string(TransportDataHeaderKey)?
       * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
       * </pre>
       *
       * <code>map&lt;string, string&gt; header = 3;</code>
       */

      public java.lang.String getHeaderOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetHeader().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearHeader() {
        internalGetMutableHeader().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * transfrom TransportDataHeaderKey to string.
       * key = "_" + TransportDataHeaderKey
       * ex: "_1", "_9"
       * 
       * Q: why donot use TransportDataHeaderKey directly?
       * A: javascript(json) doesnot support int key in object.
       * Q: why donnot use string(TransportDataHeaderKey)?
       * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
       * </pre>
       *
       * <code>map&lt;string, string&gt; header = 3;</code>
       */

      public Builder removeHeader(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableHeader().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableHeader() {
        return internalGetMutableHeader().getMutableMap();
      }
      /**
       * <pre>
       * transfrom TransportDataHeaderKey to string.
       * key = "_" + TransportDataHeaderKey
       * ex: "_1", "_9"
       * 
       * Q: why donot use TransportDataHeaderKey directly?
       * A: javascript(json) doesnot support int key in object.
       * Q: why donnot use string(TransportDataHeaderKey)?
       * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
       * </pre>
       *
       * <code>map&lt;string, string&gt; header = 3;</code>
       */
      public Builder putHeader(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableHeader().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * transfrom TransportDataHeaderKey to string.
       * key = "_" + TransportDataHeaderKey
       * ex: "_1", "_9"
       * 
       * Q: why donot use TransportDataHeaderKey directly?
       * A: javascript(json) doesnot support int key in object.
       * Q: why donnot use string(TransportDataHeaderKey)?
       * A: php treat a string with a int pattern as an int, so the probuf cannot mergeFromJsonString.
       * </pre>
       *
       * <code>map&lt;string, string&gt; header = 3;</code>
       */

      public Builder putAllHeader(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableHeader().getMutableMap()
            .putAll(values);
        return this;
      }

      private long packageId_ ;
      /**
       * <pre>
       * uniqid for blockRequest
       * the default php config doesnot support bcmath required by int64
       * </pre>
       *
       * <code>int64 packageId = 4;</code>
       */
      public long getPackageId() {
        return packageId_;
      }
      /**
       * <pre>
       * uniqid for blockRequest
       * the default php config doesnot support bcmath required by int64
       * </pre>
       *
       * <code>int64 packageId = 4;</code>
       */
      public Builder setPackageId(long value) {
        
        packageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * uniqid for blockRequest
       * the default php config doesnot support bcmath required by int64
       * </pre>
       *
       * <code>int64 packageId = 4;</code>
       */
      public Builder clearPackageId() {
        
        packageId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:core.TransportData)
    }

    // @@protoc_insertion_point(class_scope:core.TransportData)
    private static final com.zaly.proto.core.Net.TransportData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zaly.proto.core.Net.TransportData();
    }

    public static com.zaly.proto.core.Net.TransportData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransportData>
        PARSER = new com.google.protobuf.AbstractParser<TransportData>() {
      public TransportData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransportData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransportData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransportData> getParserForType() {
      return PARSER;
    }

    public com.zaly.proto.core.Net.TransportData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_TransportData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_TransportData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_TransportData_HeaderEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_TransportData_HeaderEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016core/net.proto\022\004core\032\031google/protobuf/" +
      "any.proto\"\266\001\n\rTransportData\022\016\n\006action\030\001 " +
      "\001(\t\022\"\n\004body\030\002 \001(\0132\024.google.protobuf.Any\022" +
      "/\n\006header\030\003 \003(\0132\037.core.TransportData.Hea" +
      "derEntry\022\021\n\tpackageId\030\004 \001(\003\032-\n\013HeaderEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001*\363\001\n\026T" +
      "ransportDataHeaderKey\022\021\n\rHeaderInvalid\020\000" +
      "\022\023\n\017HeaderErrorCode\020\001\022\023\n\017HeaderErrorInfo" +
      "\020\002\022\023\n\017HeaderSessionid\020\003\022\021\n\rHeaderHostUrl" +
      "\020\004\022\021\n\rHeaderReferer\020\005\022\023\n\017HeaderUserAgent" +
      "\020\006\022\024\n\020HeaderAllowCache\020\007\022\030\n\024HeaderUserCl" +
      "ientLang\020\010\022\034\n\030HeaderApplicationVersion\020\n" +
      "*@\n\022UserClientLangType\022\024\n\020UserClientLang" +
      "EN\020\000\022\024\n\020UserClientLangZH\020\001*H\n\013GatewayTyp" +
      "e\022\022\n\016GatewayInvalid\020\000\022\024\n\020GatewayWebsocke" +
      "t\020\001\022\017\n\013GatewayZaly\020\002*Y\n\016UserClientType\022\033" +
      "\n\027UserClientMobileInvalid\020\000\022\027\n\023UserClien" +
      "tMobileApp\020\001\022\021\n\rUserClientWeb\020\002*J\n\rHttpQ" +
      "ueryType\022\024\n\020HttpQueryInvalid\020\000\022\020\n\014HttpQu" +
      "eryGet\020\001\022\021\n\rHttpQueryPost\020\002*9\n\010FileType\022" +
      "\017\n\013FileInvalid\020\000\022\r\n\tFileImage\020\001\022\r\n\tFileA" +
      "udio\020\002*<\n\rDataWriteType\022\017\n\013WriteUpdate\020\000" +
      "\022\014\n\010WriteAdd\020\001\022\014\n\010WriteDel\020\002B\025\n\023com.zaly" +
      ".proto.coreb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_core_TransportData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_core_TransportData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_TransportData_descriptor,
        new java.lang.String[] { "Action", "Body", "Header", "PackageId", });
    internal_static_core_TransportData_HeaderEntry_descriptor =
      internal_static_core_TransportData_descriptor.getNestedTypes().get(0);
    internal_static_core_TransportData_HeaderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_TransportData_HeaderEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
