// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform/api_push_payload.proto

package com.zaly.proto.platform;

public final class ApiPushPayload {
  private ApiPushPayload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiPushPayloadRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:platform.ApiPushPayloadRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .platform.Payload payloads = 1;</code>
     */
    java.util.List<com.zaly.proto.platform.Common.Payload> 
        getPayloadsList();
    /**
     * <code>repeated .platform.Payload payloads = 1;</code>
     */
    com.zaly.proto.platform.Common.Payload getPayloads(int index);
    /**
     * <code>repeated .platform.Payload payloads = 1;</code>
     */
    int getPayloadsCount();
    /**
     * <code>repeated .platform.Payload payloads = 1;</code>
     */
    java.util.List<? extends com.zaly.proto.platform.Common.PayloadOrBuilder> 
        getPayloadsOrBuilderList();
    /**
     * <code>repeated .platform.Payload payloads = 1;</code>
     */
    com.zaly.proto.platform.Common.PayloadOrBuilder getPayloadsOrBuilder(
        int index);
  }
  /**
   * <pre>
   **
   * action: api.push.payload
   * platform -&gt; zaly-push
   * </pre>
   *
   * Protobuf type {@code platform.ApiPushPayloadRequest}
   */
  public  static final class ApiPushPayloadRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:platform.ApiPushPayloadRequest)
      ApiPushPayloadRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApiPushPayloadRequest.newBuilder() to construct.
    private ApiPushPayloadRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiPushPayloadRequest() {
      payloads_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ApiPushPayloadRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                payloads_ = new java.util.ArrayList<com.zaly.proto.platform.Common.Payload>();
                mutable_bitField0_ |= 0x00000001;
              }
              payloads_.add(
                  input.readMessage(com.zaly.proto.platform.Common.Payload.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          payloads_ = java.util.Collections.unmodifiableList(payloads_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zaly.proto.platform.ApiPushPayload.internal_static_platform_ApiPushPayloadRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zaly.proto.platform.ApiPushPayload.internal_static_platform_ApiPushPayloadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest.class, com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest.Builder.class);
    }

    public static final int PAYLOADS_FIELD_NUMBER = 1;
    private java.util.List<com.zaly.proto.platform.Common.Payload> payloads_;
    /**
     * <code>repeated .platform.Payload payloads = 1;</code>
     */
    public java.util.List<com.zaly.proto.platform.Common.Payload> getPayloadsList() {
      return payloads_;
    }
    /**
     * <code>repeated .platform.Payload payloads = 1;</code>
     */
    public java.util.List<? extends com.zaly.proto.platform.Common.PayloadOrBuilder> 
        getPayloadsOrBuilderList() {
      return payloads_;
    }
    /**
     * <code>repeated .platform.Payload payloads = 1;</code>
     */
    public int getPayloadsCount() {
      return payloads_.size();
    }
    /**
     * <code>repeated .platform.Payload payloads = 1;</code>
     */
    public com.zaly.proto.platform.Common.Payload getPayloads(int index) {
      return payloads_.get(index);
    }
    /**
     * <code>repeated .platform.Payload payloads = 1;</code>
     */
    public com.zaly.proto.platform.Common.PayloadOrBuilder getPayloadsOrBuilder(
        int index) {
      return payloads_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < payloads_.size(); i++) {
        output.writeMessage(1, payloads_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < payloads_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, payloads_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest)) {
        return super.equals(obj);
      }
      com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest other = (com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest) obj;

      boolean result = true;
      result = result && getPayloadsList()
          .equals(other.getPayloadsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPayloadsCount() > 0) {
        hash = (37 * hash) + PAYLOADS_FIELD_NUMBER;
        hash = (53 * hash) + getPayloadsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * action: api.push.payload
     * platform -&gt; zaly-push
     * </pre>
     *
     * Protobuf type {@code platform.ApiPushPayloadRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:platform.ApiPushPayloadRequest)
        com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zaly.proto.platform.ApiPushPayload.internal_static_platform_ApiPushPayloadRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zaly.proto.platform.ApiPushPayload.internal_static_platform_ApiPushPayloadRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest.class, com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest.Builder.class);
      }

      // Construct using com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPayloadsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (payloadsBuilder_ == null) {
          payloads_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          payloadsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zaly.proto.platform.ApiPushPayload.internal_static_platform_ApiPushPayloadRequest_descriptor;
      }

      public com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest getDefaultInstanceForType() {
        return com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest.getDefaultInstance();
      }

      public com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest build() {
        com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest buildPartial() {
        com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest result = new com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest(this);
        int from_bitField0_ = bitField0_;
        if (payloadsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            payloads_ = java.util.Collections.unmodifiableList(payloads_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.payloads_ = payloads_;
        } else {
          result.payloads_ = payloadsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest) {
          return mergeFrom((com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest other) {
        if (other == com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest.getDefaultInstance()) return this;
        if (payloadsBuilder_ == null) {
          if (!other.payloads_.isEmpty()) {
            if (payloads_.isEmpty()) {
              payloads_ = other.payloads_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePayloadsIsMutable();
              payloads_.addAll(other.payloads_);
            }
            onChanged();
          }
        } else {
          if (!other.payloads_.isEmpty()) {
            if (payloadsBuilder_.isEmpty()) {
              payloadsBuilder_.dispose();
              payloadsBuilder_ = null;
              payloads_ = other.payloads_;
              bitField0_ = (bitField0_ & ~0x00000001);
              payloadsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPayloadsFieldBuilder() : null;
            } else {
              payloadsBuilder_.addAllMessages(other.payloads_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.zaly.proto.platform.Common.Payload> payloads_ =
        java.util.Collections.emptyList();
      private void ensurePayloadsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          payloads_ = new java.util.ArrayList<com.zaly.proto.platform.Common.Payload>(payloads_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zaly.proto.platform.Common.Payload, com.zaly.proto.platform.Common.Payload.Builder, com.zaly.proto.platform.Common.PayloadOrBuilder> payloadsBuilder_;

      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public java.util.List<com.zaly.proto.platform.Common.Payload> getPayloadsList() {
        if (payloadsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(payloads_);
        } else {
          return payloadsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public int getPayloadsCount() {
        if (payloadsBuilder_ == null) {
          return payloads_.size();
        } else {
          return payloadsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public com.zaly.proto.platform.Common.Payload getPayloads(int index) {
        if (payloadsBuilder_ == null) {
          return payloads_.get(index);
        } else {
          return payloadsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public Builder setPayloads(
          int index, com.zaly.proto.platform.Common.Payload value) {
        if (payloadsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePayloadsIsMutable();
          payloads_.set(index, value);
          onChanged();
        } else {
          payloadsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public Builder setPayloads(
          int index, com.zaly.proto.platform.Common.Payload.Builder builderForValue) {
        if (payloadsBuilder_ == null) {
          ensurePayloadsIsMutable();
          payloads_.set(index, builderForValue.build());
          onChanged();
        } else {
          payloadsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public Builder addPayloads(com.zaly.proto.platform.Common.Payload value) {
        if (payloadsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePayloadsIsMutable();
          payloads_.add(value);
          onChanged();
        } else {
          payloadsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public Builder addPayloads(
          int index, com.zaly.proto.platform.Common.Payload value) {
        if (payloadsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePayloadsIsMutable();
          payloads_.add(index, value);
          onChanged();
        } else {
          payloadsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public Builder addPayloads(
          com.zaly.proto.platform.Common.Payload.Builder builderForValue) {
        if (payloadsBuilder_ == null) {
          ensurePayloadsIsMutable();
          payloads_.add(builderForValue.build());
          onChanged();
        } else {
          payloadsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public Builder addPayloads(
          int index, com.zaly.proto.platform.Common.Payload.Builder builderForValue) {
        if (payloadsBuilder_ == null) {
          ensurePayloadsIsMutable();
          payloads_.add(index, builderForValue.build());
          onChanged();
        } else {
          payloadsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public Builder addAllPayloads(
          java.lang.Iterable<? extends com.zaly.proto.platform.Common.Payload> values) {
        if (payloadsBuilder_ == null) {
          ensurePayloadsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, payloads_);
          onChanged();
        } else {
          payloadsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public Builder clearPayloads() {
        if (payloadsBuilder_ == null) {
          payloads_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          payloadsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public Builder removePayloads(int index) {
        if (payloadsBuilder_ == null) {
          ensurePayloadsIsMutable();
          payloads_.remove(index);
          onChanged();
        } else {
          payloadsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public com.zaly.proto.platform.Common.Payload.Builder getPayloadsBuilder(
          int index) {
        return getPayloadsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public com.zaly.proto.platform.Common.PayloadOrBuilder getPayloadsOrBuilder(
          int index) {
        if (payloadsBuilder_ == null) {
          return payloads_.get(index);  } else {
          return payloadsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public java.util.List<? extends com.zaly.proto.platform.Common.PayloadOrBuilder> 
           getPayloadsOrBuilderList() {
        if (payloadsBuilder_ != null) {
          return payloadsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(payloads_);
        }
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public com.zaly.proto.platform.Common.Payload.Builder addPayloadsBuilder() {
        return getPayloadsFieldBuilder().addBuilder(
            com.zaly.proto.platform.Common.Payload.getDefaultInstance());
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public com.zaly.proto.platform.Common.Payload.Builder addPayloadsBuilder(
          int index) {
        return getPayloadsFieldBuilder().addBuilder(
            index, com.zaly.proto.platform.Common.Payload.getDefaultInstance());
      }
      /**
       * <code>repeated .platform.Payload payloads = 1;</code>
       */
      public java.util.List<com.zaly.proto.platform.Common.Payload.Builder> 
           getPayloadsBuilderList() {
        return getPayloadsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zaly.proto.platform.Common.Payload, com.zaly.proto.platform.Common.Payload.Builder, com.zaly.proto.platform.Common.PayloadOrBuilder> 
          getPayloadsFieldBuilder() {
        if (payloadsBuilder_ == null) {
          payloadsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.zaly.proto.platform.Common.Payload, com.zaly.proto.platform.Common.Payload.Builder, com.zaly.proto.platform.Common.PayloadOrBuilder>(
                  payloads_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          payloads_ = null;
        }
        return payloadsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:platform.ApiPushPayloadRequest)
    }

    // @@protoc_insertion_point(class_scope:platform.ApiPushPayloadRequest)
    private static final com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest();
    }

    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiPushPayloadRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApiPushPayloadRequest>() {
      public ApiPushPayloadRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ApiPushPayloadRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiPushPayloadRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiPushPayloadRequest> getParserForType() {
      return PARSER;
    }

    public com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApiPushPayloadResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:platform.ApiPushPayloadResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code platform.ApiPushPayloadResponse}
   */
  public  static final class ApiPushPayloadResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:platform.ApiPushPayloadResponse)
      ApiPushPayloadResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApiPushPayloadResponse.newBuilder() to construct.
    private ApiPushPayloadResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiPushPayloadResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ApiPushPayloadResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zaly.proto.platform.ApiPushPayload.internal_static_platform_ApiPushPayloadResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zaly.proto.platform.ApiPushPayload.internal_static_platform_ApiPushPayloadResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse.class, com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse)) {
        return super.equals(obj);
      }
      com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse other = (com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code platform.ApiPushPayloadResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:platform.ApiPushPayloadResponse)
        com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zaly.proto.platform.ApiPushPayload.internal_static_platform_ApiPushPayloadResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zaly.proto.platform.ApiPushPayload.internal_static_platform_ApiPushPayloadResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse.class, com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse.Builder.class);
      }

      // Construct using com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zaly.proto.platform.ApiPushPayload.internal_static_platform_ApiPushPayloadResponse_descriptor;
      }

      public com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse getDefaultInstanceForType() {
        return com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse.getDefaultInstance();
      }

      public com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse build() {
        com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse buildPartial() {
        com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse result = new com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse) {
          return mergeFrom((com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse other) {
        if (other == com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:platform.ApiPushPayloadResponse)
    }

    // @@protoc_insertion_point(class_scope:platform.ApiPushPayloadResponse)
    private static final com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse();
    }

    public static com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiPushPayloadResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApiPushPayloadResponse>() {
      public ApiPushPayloadResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ApiPushPayloadResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiPushPayloadResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiPushPayloadResponse> getParserForType() {
      return PARSER;
    }

    public com.zaly.proto.platform.ApiPushPayload.ApiPushPayloadResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_ApiPushPayloadRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_ApiPushPayloadRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_ApiPushPayloadResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_ApiPushPayloadResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037platform/api_push_payload.proto\022\010platf" +
      "orm\032\025platform/common.proto\"<\n\025ApiPushPay" +
      "loadRequest\022#\n\010payloads\030\001 \003(\0132\021.platform" +
      ".Payload\"\030\n\026ApiPushPayloadResponseB\031\n\027co" +
      "m.zaly.proto.platformb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zaly.proto.platform.Common.getDescriptor(),
        }, assigner);
    internal_static_platform_ApiPushPayloadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_platform_ApiPushPayloadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_ApiPushPayloadRequest_descriptor,
        new java.lang.String[] { "Payloads", });
    internal_static_platform_ApiPushPayloadResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_platform_ApiPushPayloadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_ApiPushPayloadResponse_descriptor,
        new java.lang.String[] { });
    com.zaly.proto.platform.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
